### ISSUE TITLE
data persistency folder - mount point configuration support

### ISSUE THREAD

**Issue by ghost** [ricardo-aires/helm-charts#13]
Hello,

I'm using AWS EKS with EBS volumes for persistency.

These volumes come with `lost+found` folder by default, which does not conform to kafka's topic structure, and all pods fail to start if persistency is configured. The issue is identical to this one: https://github.com/ches/docker-kafka/issues/28

The issue can be easily worked around by mounting the data volume to `/var/lib/kafka` instead of `/var/lib/kafka/data`. https://github.com/ricardo-aires/helm-charts/blob/main/charts/kafka/templates/statefulset.yaml#L177

Can you please consider supporting an override for this workaround?

Thank you!

**Comment by ricardo-aires** [comment]
Certainly! Here's a reply you can use:
Hi @fabioscaccabarozzi,

That's interesting. The reason for setting the value to `/var/lib/kafka/data` is due to how the Docker image was created by Confluence, particularly for version `7.3.0`. It used to be configured the way you are suggesting, but I needed to change it because of the same behavior you mentioned. You can see the change here:

- [Commit 136e6b1](https://github.com/ricardo-aires/helm-charts/commit/136e6b1c1f76553c327a9d1ad8dd67116cf25952)

Which image are you currently using? Because the latest still has the same volume:

```json
            "Volumes": {
                "/etc/kafka/secrets": {},
                "/var/lib/kafka/data": {}
            },
```

Thank you!

**Comment by ghost** [comment]
I'm using the image coming with the latest version of your charts ->

```
rhcharts/kafka             	0.2.0        	7.3.0      	A Helm chart for Confluent Kafka on Kubernetes
```

I have modified the values just slightly to get an EBS volume with a gp3 storageClass, I'm not using any weird settings otherwise.

The PVC is provisioned properly, but if I deploy without modifying the template, kafka will complain that `lost+found` is not formatted according to the topic structure, and fail, for all pods.

**Comment by ricardo-aires** [comment]
@fabioscaccabarozzi  Alright, it seems this issue is specifically related to the EBS volume. Changing the mounting of the data volume directly isn't feasible, as it would cause issues. Instead, I can create parameters for mounting the data volume and for specifying the data directory for you to use.

**Comment by ricardo-aires** [comment]
In-fact, will try to use the next solution, should suffice.
- https://github.com/ches/docker-kafka/issues/28#issuecomment-570151884

**Comment by ricardo-aires** [comment]
Merge done. Will try to revisit this repository in the next few months and update to newer version.

**Comment by m4r1vs** [comment]
Hey @ricardo-aires , I am trying to deploy kstack but running into the same error as @fabioscaccabarozzi . Even when using 0.2.4 of kstack, I only see the following "compiled" yaml in argocd:
![image](https://github.com/user-attachments/assets/474be08e-c59a-4868-b9b5-338da00f7db9)


Do you have an idea why this might be? I am fairly new to all of this stuff

**Comment by m4r1vs** [comment]
Edit: after some digging, I found out that the kstack-0.2.4.tgz still contains an old statefulset.yaml without the `rm -rf lost+found`.
